### ISSUE TITLE
Duracion al apagar

### ISSUE THREAD

**Issue by ADOCR** [cslucr/ubuntu-ucr#13]
Suele durar mucho a la hora de apagar la maquina, especialmente luego de estar utilizando el _JDK_ de java o entornos de desarrollo para _python._

**Comment by valarauco** [comment]
En el Issue que se publicó en el repo de Leo, @luisza mencionó [esta](https://freedesktop.org/wiki/Software/systemd/Debugging/#shutdowncompleteseventually)[1] técnica para generar un log de debug.
Será que nos puedes generar el log de cuando tarda mucho para revisarlo?

[1] https://freedesktop.org/wiki/Software/systemd/Debugging/#shutdowncompleteseventually

**Comment by ADOCR** [comment]
el jueves lo genero, y lo agrego.

**Comment by leojimenezcr** [comment]
Me ha pasado en casos aislados, cuando el Ubuntu queda esperando a que finalice alguna tarea. Presionando "Esc" en ese momento mostrará la información de salida del proceso de apagado.
