### ISSUE TITLE
Ubuntu MATE no aplica borde de ventana Ark-Dark de manera predeterminada

### ISSUE THREAD

**Issue by leojimenezcr** [cslucr/ubuntu-ucr#18]
En Ubuntu MATE se aplica el tema gtk Ark-Darker sin embargo no aplica el borde de ventana Ark-Dark de manera predeterminada. Muy probablemente hay que revisar el respectivo archivo .override

**Comment by luisza** [comment]
Parece que PR #56 resuelve también esto,  pero aplica borde de ventana Ark-Darker o es Ark-Dark lo que debería ir?

**Comment by leojimenezcr** [comment]
Si, es el tema Ark-Darker
