### ISSUE TITLE
Repos de Firma digital no disponibles

### ISSUE THREAD

**Issue by valarauco** [cslucr/ubuntu-ucr#29]
El repositorios para los paquetes de firma digital de Costa Rica no están disponible dentro de la red de la UCR (Donde se construye el ISO):
> Err:2 http://repos.solvosoft.com/ubuntu xenial InRelease
>   Could not resolve 'repos.solvosoft.com'

**Comment by valarauco** [comment]
Revisé en [downforeveryoneorjustme.com](http://downforeveryoneorjustme.com/repos.solvosoft.com) y parece ser un problema de DNS internamente.

Lo reporté a los encargados de servicio para ver que puede ser.

**Comment by valarauco** [comment]
Según me comentan los compañeros, parece ser una incongruencia en la configuración de los DNS Autoritativos asociados al dominio, al hacer la consulta se listan estos:
```
;; AUTHORITY SECTION:
solvosoft.com.		3600	IN	NS	ns2.myhosting.com.
solvosoft.com.		3600	IN	NS	ns2.solvosoft.com.
solvosoft.com.		3600	IN	NS	ns.myhosting.com.
solvosoft.com.		3600	IN	NS	ns1.myhosting.com.
solvosoft.com.		3600	IN	NS	ns1.solvosoft.com.
```
Sin embargo, ns1.solvosoft.com y ns2.solvosoft.com (que poseen la misma IP) parecen no tener los datos correctos de la zona asociada al dominio y no resuelven correctamente repos.solvosoft.com; además poseen un tiempo de cache de 10800 segundos.

Lo que sucedió fue que el DNS de la U cachó el dato espurio de esos dos servidores y no iba a refrescar ese cache sino hasta 10800 segundos después. Al final se reseteó el cache pero el problema puede volver a pasar si se cachea nuevamente desde alguno de esos equipos.

cc @luisza, voy a crear un issue en el repo de Solvo como para que el dato quede ahí, pero me recomiendan que lo más sencillo es actualizar los datos de los DNS que tiene problema.

**Comment by luisza** [comment]
Hola,

Si, he eliminado los 2 ns correspondiente a ns2.solvosoft.com y ns1.solvosoft.com,  que se encontraban desactualizados.   En buena teoría después de unas cuantas horas quedarán los dns base de forma que no pase lo de las caches.

**Comment by valarauco** [comment]
Genial! Muchas gracias!
Ya se ve reflejado en los NS... creo que podemos dar por cerrado el issue.

Pura vida!
