### ISSUE TITLE
ubuntu-ucr-text.so no existe

### ISSUE THREAD

**Issue by luisza** [cslucr/ubuntu-ucr#3]
Este mensaje se muestra al crear el iso 

W: plymouth module (/usr/lib/x86_64-linux-gnu/plymouth//ubuntu-ucr-text.so) missing, skipping that theme.

Recordar que muchos .gitignore por defecto ignoran los .so.

**Comment by valarauco** [comment]
Estoy viendo ese mismo mensaje de error durante la instalación del ISO construido con GitlabCI

**Comment by leojimenezcr** [comment]
Me parece que omití ese archivo creyendo que no se necesitaba. Hay que revisar el ISO original para copiarlo y renombrarlo si es el caso. ubuntu-ucr-text es el tema en modo de texto original con algunas modificaciones.
