### ISSUE TITLE
Cache para apt es ineficiente y provoca problemas de permisos.

### ISSUE THREAD

**Issue by luisza** [cslucr/ubuntu-ucr#37]
En mi versión el sistema de cache de apt (gran funcionalidad, no copia adecuadamente la carpeta ).
Considero que se debe documentar mejor cual es la carpeta que hay que montar y el contenido de la misma, pero aún así cuando la carpeta está correcta y se corre con un usuario sin permisos el sistema falla.

Considero que es mejor opción usar un mount -o bind $carpeta_cache /var/cache/apt/.

**Comment by valarauco** [comment]
Ciertamente es un proceso ineficiente y las funcionalidad fue creada inicialmente para el CI y probada solo ahí para ahorrar tiempo y ancho de banda. 
También pensé en usar mount o symlinks, el problema es que en chroot el script de la personalización ejecuta apt clean para limpiar el cache de APT (lo cual es correcto dado que el ISO debe ir lo más limpio posible) pero entonces en un mount borraría lo que está ahí o me equivoco?

Pensé en usar enlaces duros para evitar perder los paquetes y ahorrar espacio en disco durante el proceso, pero claramente el proceso se hizo engorroso. Otra opción, mas adecuada, es utilizar un APT-Cacher en lugar de la carpeta de cache, pero implica instalar un componente adicional.

**Comment by luisza** [comment]
Yo estoy trabajando en una versión basada en mount, que no borre los paquetes, adicionalmente trabajo en el cache de wget.  Anoche estuve trabajando y creo que ya está solo ocupo un poco más de pruebas para verificar.

Esto sería muy bueno porque dura bastante descargando paquetes y demás +400mb de actualizaciones y contando.

**Comment by luisza** [comment]
PR  #53 resuelve esto.
