### ISSUE TITLE
Eliminar arranque automático de cliente de firma digital

### ISSUE THREAD

**Issue by luisza** [cslucr/ubuntu-ucr#38]
Actualmente, cuando se inicia una sesión se abre el cliente de firma digital y comprueba si tiene acceso o el dispositivo conectado y si no lanza un mensaje muy feo al usuario.
Este cliente no es muy popular ya que firma digital a penas se está popularizando por lo que sería mejor desactivar el autoarranque .

**Comment by leojimenezcr** [comment]
Me parece que el paquete añade un .desktop a /etc/skel, si no me equivoco. Tal vez se podría añadir una línea que borre ese archivo después de instalar el paquete.

**Comment by luisza** [comment]
#54 resuelve este issue
