### ISSUE TITLE
Agregar firmware común para dispositivos inalámbricos

### ISSUE THREAD

**Issue by luisza** [cslucr/ubuntu-ucr#40]
Algunos paquetes como **linux-firmware firmware-b43-installer** podrían ser de utilidad para soportar el mayor número de tarjetas wifi y ethernet.

**Comment by luisza** [comment]
see #41

**Comment by valarauco** [comment]
Que tanta basura meten esos dos paquetes? en el sentido de que si tener esos paquetes podría afectar al sistema en rendimiento o seguridad

**Comment by leojimenezcr** [comment]
Me parece que la "basura" que mete no es tanto, tomando en cuenta que la imagen de todos modos pesa 2.5 GB y sería una gran ventaja para el usuario incluir drivers que va a necesitar.

**Comment by leojimenezcr** [comment]
Añadidos esos paquetes en PR #41
