### ISSUE TITLE
Salida inexperada provoca problemas en el sistema anfitrión

### ISSUE THREAD

**Issue by luisza** [cslucr/ubuntu-ucr#42]
Hace unos minutos, hice un cambio que provocó un error en la instalación, llamando a **error_exit "mensaje"**, el sistema terminó de inmediato y dejó muchas cosas montadas, provocando que los tty fallaran.

viendo un poco el código, veo que la salida abrunta del programa provoca este tipo de situaciones. Por lo que sería recomendable mejorar la forma como termina el programa y verificar que todo lo montado se desmonte.

**Comment by leojimenezcr** [comment]
En los commits 7a20f7b19c0992ad0cffac88fa3fb8d573a5b883 y faff0fa50a2e58391d996d77bea46820b9020856 se trabajan esos errores.
