### ISSUE TITLE
Se configuran las plantillas antes de instalar LibO

### ISSUE THREAD

**Issue by valarauco** [cslucr/ubuntu-ucr#46]
Durante la personalización se instalan las plantillas de LibreOffice antes de ejecutar la actualización de los paquetes de libreOffice desde el PPA

https://github.com/cslucr/ubuntu-ucr/blob/67d526adf7f218d3d6ea4789ef21d65d5ae0c04e/ubuntu-16.04-ucr-config.sh#L157

Lo ideal sería cambiar esta linea más abajo

**Comment by leojimenezcr** [comment]
Corregido en #47
