### ISSUE TITLE
Eliminar traducciones y programas antes de hacer update de la distro

### ISSUE THREAD

**Issue by luisza** [cslucr/ubuntu-ucr#49]
Algunos paquetes que podríamos eliminar son:

1. Libreoffice 
 libreoffice-help-fr libreoffice-help-it libreoffice-help-pt libreoffice-help-pt-br libreoffice-help-ru
  libreoffice-help-zh-cn libreoffice-help-zh-tw  libreoffice-l10n-de libreoffice-l10n-en-gb
  libreoffice-l10n-en-za  libreoffice-l10n-fr libreoffice-l10n-it libreoffice-l10n-pt libreoffice-l10n-pt-br
  libreoffice-l10n-ru libreoffice-l10n-zh-cn libreoffice-l10n-zh-tw

2. Firefox
firefox-locale-de firefox-locale-fr firefox-locale-it firefox-locale-pt firefox-locale-ru firefox-locale-zh-hans

3. Thunderbird
thunderbird-locale-de thunderbird-locale-en-gb thunderbird-locale-es-ar thunderbird-locale-es-es thunderbird-locale-fr thunderbird-locale-it thunderbird-locale-pt thunderbird-locale-pt-br thunderbird-locale-pt-pt thunderbird-locale-ru thunderbird-locale-zh-cn thunderbird-locale-zh-hans   thunderbird-locale-zh-hant thunderbird-locale-zh-tw

4. Evolution y otros 
evolution evolution-plugins evolution-common libevolution evolution-data-server-online-accounts tilda

Estos se desinstalarían antes de proceder a actualizar el sistema para ahorrar tiempo de descarga e instalación de paquetes que se van eliminar

**Comment by leojimenezcr** [comment]
Me parece muy bien, hay que completar la lista de archivos a purgar y probar correr el `apt purge` antes de todo del `dist-upgrade`

**Comment by amekare** [comment]
Yo me encargo de revisar este issue

**Comment by valarauco** [comment]
#58 resuelve este issue?

**Comment by leojimenezcr** [comment]
Efectivamente
