### ISSUE TITLE
Error al compilar relocatable schemas de archivos override

### ISSUE THREAD

**Issue by leojimenezcr** [cslucr/ubuntu-ucr#50]
Al compilar archivos de schemas con `glib-compile-schemas`, los _relocatable schemas_ son ignorados, es decir los que son de la forma: schema:path, por ejemplo:
[org.mate.panel.object:/org/mate/panel/objects/mate-menu/]

El bug está descrito en:
https://bugs.launchpad.net/ubuntu/+source/glib2.0/+bug/1281580

Este usuario lo resuelve yendo más bajo, creando archivos de configuración:
https://blog.chapus.net/more-gnome-unity-system-defaults/

**Comment by luisza** [comment]
Creo que es mejor utilizando dconf (por lo menos por ahora, mientras se completa la transición de gsettings), ésta página me ayudó mucho https://lauri.võsandi.com/2015/03/dconf.html.  

Otra cosa, cuando haya algo que falle, pero que quiera compartir utilice un branch aparte del master, con esto otros podemos ver sus cambios y no rompemos el programa con cosas inestables.

**Comment by leojimenezcr** [comment]
El Pull request #56 aplica el esquema de una forma alternativa, de manera que resuelve la necesidad.
