### ISSUE TITLE
Tools e IDEs para Desarrolladores

### ISSUE THREAD

**Issue by josechavarriacr** [cslucr/ubuntu-ucr#55]
Estaba pensando en crear Scripts que instalen los packetes e IDEs para Desarrolladores y estudiantes que lo necesiten para programar y esos Scripts se pueden guardar en algún directorio, que les parece la idea?

**Comment by leojimenezcr** [comment]
Esto es un tema que estuvimos discutiendo. También se pueden hacer recetas para añadir personalizaciones para desarrolladores, diseñadores, músicos, etc.

La pregunta es: ¿Cómo manejamos eso? ¿Paquetes extras que hagan la tarea? (porque también se discute el armar un paquete deb que ejecute y actualice la personalización)

**Comment by josechavarriacr** [comment]
Yo estaba pensado en crear algún software con menu para instalar y desinstalar los paquetes necesarios para correr las herramientas y dicho paquete puede tener los scripts para acutlización.
Algo como esto 
![687474703a2f2f676172746876682e636f6d2f6173736574732f696d672f746f75636870692f6d656e755f38627574746f6e2e6a7067](https://user-images.githubusercontent.com/15972021/32005667-154abefa-b962-11e7-9a0f-3385077abf8c.jpg)

**Comment by luisza** [comment]
Y cual sería la diferencia con respecto a software boutique en la pestaña de desarrollador.

![screenshot_cslucr_2017-10-25_23 33 23](https://user-images.githubusercontent.com/7146904/32036426-fb9dd02a-b9dc-11e7-9efc-13db73525338.png)

**Comment by amekare** [comment]
@luisza yo creería que se pondría software recomendado, es decir utilizado por la comunidad, porque hay muchas herramientas y con varios sabores

**Comment by luisza** [comment]
Sip, se podría recopilar la información de las hererramientas usadas en la U,  catalogarlas y generar algún instalador basado en temáticas. (talvez si hacemos paquetes deb o alguien aporte metapaquetes de taskel)

**Comment by leojimenezcr** [comment]
Creo que tendremos que escribir documentación tipo "Cosas que hacer después de instalar Ubuntu UCR" donde se hablen de esos paquetes extras, formas de personalizar el entorno, etc.
