### ISSUE TITLE
Instalador de Ubuntu desaperece al crear ISO

### ISSUE THREAD

**Issue by rlmrjmnz** [cslucr/ubuntu-ucr#64]
Al momento de crear una nueva ISO con la última versión de desarrollo de Ubuntu-UCR, tanto en Unity como en Mate, desaparece el instalador de Ubuntu, por lo que es imposible poder instalar el sistema operativo.

Si se escoge la opción de "Instalar" cuando se bootea desde la ISO esta automáticamente arranca la _session-live_.

Estos errores no se presentaban con la versión del script utilizado alrededor del 28 de octubre para la generación de ISOs.

**Comment by leojimenezcr** [comment]
Adjunto los logs en _/var/log/apt/_ después de generar el ISO el día de ayer. Se observa que remueve los paquetes **ubiquity** y **ubiquity-frontend-gtk** durante la ejecución de **apt-get -y dist-upgrade**.

[history.log](https://github.com/cslucr/ubuntu-ucr/files/1462582/history.log)
[term.log](https://github.com/cslucr/ubuntu-ucr/files/1462583/term.log)

**Comment by valarauco** [comment]
Acabo de ejecutar un live CD de Ubuntu 16.04 y sin nada más intenté correr un `apt dist-upgrade` y esta acción intenta desinstalar el paquete ubiquity (encargado del instalador)

Lo extraño es que el dist-upgrade ha estado desde el primer commit del script 😱

**Comment by valarauco** [comment]
Al parecer al actualizar el paquete `ubiquity-ubuntu-artwork`  se remueve el paquete ubiquity
![apt install ubiquity-ubuntu-artwork](https://user-images.githubusercontent.com/434898/32678352-9889a2be-c627-11e7-8c20-2c96dc409d53.png)

En las dependencias el paquete informa que reemplaza al paquete `ubiquity`
![apt show ubiquity-ubuntu-artwork](https://user-images.githubusercontent.com/434898/32678459-06b151e2-c628-11e7-8af4-0e0bdb4b79ac.png)

Desconozco si es un error de empaquetamiento o si es algo premeditado

Es más, ubiquity no se puede instalar pues depende de `console-setup >= 1.108ubuntu15.4` y la versión disponible al parecer es `1.108ubuntu15.3`

**Comment by valarauco** [comment]
Parece ser que el error fue introducido por una actualización del paquete.
En [launchpad](https://launchpad.net/ubuntu/xenial/+source/ubiquity/+changelog) está propuesta la actualización que revierte la dependencia rota de `console-setup`.

Por ahora solo queda esperar que empujen esa actualización a los repositorios.

**Comment by leojimenezcr** [comment]
En el commit bf43ae9a333abe6e904f072795a481195f83a5c7 agregué un `apt-mark hold ubiquity` como parche temporal

![screenshot at 2017-11-10 15 34 21](https://user-images.githubusercontent.com/6515809/32681272-4d7fcdea-c634-11e7-9e88-1b93164e04f9.png)
