### ISSUE TITLE
Manejo de errores en script bash ubuntu-iso-customization.sh

### ISSUE THREAD

**Issue by leojimenezcr** [cslucr/ubuntu-ucr#8]
El script para generar el ISO no tiene un _error handling_ que nos asegure que todos los pasos se ejecuten adecuadamente.

En este caso deberían añadirse comprobaciones a comandos importantes, por ejemplo que la salida de estos sea exitosa, revisando que la variable $? sea igual a 0 (de las muchas opciones que hay).

Así:
```
comando importante
if [ $? -eq 0 ];
then
  echo "Éxito"
else
  echo "Fallo"
  exit 1
fi
```

**Comment by valarauco** [comment]
Algo a tomar en cuanta es que #30 maneja cualquier fallo como un error fatal y sale. 
Sería bueno evaluar si es necesario tratar algunos de esos errores como warnings y no necesariamente detener el script
